version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27016:27017'
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  backend:
    build: ./microServiceRAPI
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb+srv://schnatr:vcS0AQDhqKWSi6Tc@clusterzero.6uzvv.mongodb.net/?retryWrites=true&w=majority&appName=ClusterZero
    deploy:
      replicas: 1
      restart_policy:
        condition: any